### ISSUE TITLE
Website's other tabs on GitHub pages runs 404 error

### ISSUE THREAD

**Issue by KasinadhuniProgrammer** [KasinadhuniProgrammer/SoftAce#1]
On the SoftAce website, we have other tabs such as the live streaming section, the coding interviews section, etc. When you enter the home page you should be able to access these pages by clicking on the <a> tag corresponding to that page. GitHub pages is running a 404 error saying page is not found when trying to go on different pages. For example, I go to SoftAce's github pages site, I click on live streams, but when I do it says 404 "There isn't a GitHub Pages site here."

**Comment by ftc12923** [comment]
I am willing to try to find a solution

**Comment by KasinadhuniProgrammer** [comment]
@ftc12923 great, thank you! I appreciate it :)

**Comment by ftc12923** [comment]
I am going to be honest, I think you should try to switch to something else like Vercel, to be honest, Vercel is the best one, this is a common problem with react.js and Github pages

**Comment by KasinadhuniProgrammer** [comment]
@ftc12923 yeah I heard some other people that I reached out to talk about Vercel and they were saying I should deploy this on there instead, I'll look into it, thanks for your help!
